### ISSUE TITLE
Would this work with Ref<?> inside User?

### ISSUE THREAD

**Issue by slugmandrew** [freddyboucher/gwt-storage-objectify#4]
Hey buddy, interesting little project you've got here. I thought I was the only person using GWT and GAE left! :) I'm def going to fork it and have a little play about with it.

Quick one... I've recently been playing with local storage myself and it's pretty nifty, but I use DTOs throughout my app as I've found a lot a of issues in the past with Ref<?>. As I understand it adding objectify-gwt into a project allows you to pass Key<?> to the client side but not Ref<?>, is that right?

**Comment by freddyboucher** [comment]
Hey,
Glad you find this little project helpful.
First of all, **objectify-gwt** is useful only is you use GWT RPC to transfer your Entities.
And you're wrong, you can use **Key** as well as **Ref** in your client code.
On **master** branch, as you see my [GreetingResponse](https://github.com/freddyboucher/gwt-storage-objectify/blob/master/gwt-storage-objectify-shared/src/main/java/com/project/shared/entities/GreetingResponse.java#L18) Entity has a **Ref\<User>** field.

I'm currently switching away from **GWT RPC** in favor of **Rest** but I want to keep my Entities as it is (with **Key** and **Ref**).
The work in progress branch is [gwt-jackson-objectify](https://github.com/freddyboucher/gwt-storage-objectify/commits/gwt-jackson-objectify).

To do so I'm implementing a new **gwt-jackson extension** to support objectify: https://github.com/freddyboucher/gwt-jackson/commits/objectify

It's almost ready, but I have one open issue https://github.com/nmorel/gwt-jackson/issues/121

I will keep you in touch when it's ready.
Cheers

**Comment by freddyboucher** [comment]
@slugmandrew 
Just to let you know that I've just completed the migration to REST/JSON, it's already live on master.
I created a new [gwt-jackson-objectify](https://github.com/nmorel/gwt-jackson/tree/master/extensions/objectify) that is available on Maven since yesterday https://mvnrepository.com/artifact/com.github.nmorel.gwtjackson/gwt-jackson/0.15.0

**Comment by slugmandrew** [comment]
Cheers for the update. Apologies for not getting back to you but I have ended up moving away from Objectify towards a more traditional data storage solution as it better suited my needs. If I need to use it anytime soon I'll definitely check this out!
