### ISSUE TITLE
install does not work

### ISSUE THREAD

**Issue by preitinger** [freddyboucher/gwt-storage-objectify#7]
blocking at:
Downloading from sonatype.snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/classmate/1.3.4/classmate-1.3.4.jar

**Comment by preitinger** [comment]
I thought i had FINALLY found a really working example for nowadays eclipse with gwt and gae and objectify but AGAIN of course it does not work. Sorry for my real huge frustration!

**Comment by preitinger** [comment]
Sorry not very used to git. I thought I "close" the comment, not the issue...

**Comment by freddyboucher** [comment]
It should work!
Which maven command did you run?
